### ISSUE TITLE
Low vaccum pressure fix not applied?

### ISSUE THREAD

**Issue by sandpatch** [gdzx/chernobyl-simulator#1]
Thanks for your work. I have problems getting vacuum when running the Chr004.icd. Has the Chr004.icd ben applied?

https://www.youtube.com/watch?v=PZMAwTGXLb8

**Comment by gdzx** [comment]
Hi,

Glad you're enjoying this game!

You don't have to patch `chr004.icd` (this is a workaround for the bugs in the remastered version). As you can see in the following screenshot, I could get the condenser vacuum system to work with these initial conditions:

![condenser-vacuum](https://user-images.githubusercontent.com/6490707/202809986-1bcc9507-e96b-4a7e-ac22-221754a71d5b.png)

First of all, check the following items (these are prerequisites for the air ejectors to work, but if you followed the step-by-step plant start-up procedure you should be ok):

- Is the turbine on turning gear with the steam seals on?
- Is the vacuum breaker closed?
- Do you have at least 250 psig of main steam pressure?

In this version of the game, there are silent malfunctions that you have to uncover yourself (sometimes by just trying to operate the faulty system until you get the repair prompt). But for the other kind of malfunctions, you may find the _Repairs / Replacement_ menu helpful... (Note that while you can disable malfunctions from the _Extras_ menu, that doesn't apply to what is already defined by the initial conditions.)

Let me know if you need some spoilers :)

**Comment by sandpatch** [comment]
Hmm, now I did get it to work. 
The other 3 times, no matter how much I fixed it never got to full vacuum. I could fix it, then it got a slight amount of vacuum before going back. Maybe there is a pressure limit on fixing it? 

I have no clue.

**Comment by gdzx** [comment]
The other things I can think of (although I won't be able to test them right now) are:

- Condenser tube leaks if you are just above 250 psig, maybe that's enough to prevent the air ejectors from working properly (you can check if the condensate polisher unit exhausts itself or if the conductivity increases).
- Main steam dump setpoint set too low, steam dump valve not in auto, or malfunctioning (check the main steam pressure when you start the steam air ejectors: you can set the setpoint to 350 psig and it should stay above 250 psig from decay heat alone).
- Ruptured condenser diaphragm (though that shouldn't be the case at the start of this scenario, I don't think you would get any amount of vacuum if that was the case, and 350 psig should be under the limit).
- Low decay heat due to depleted fuel, maybe high xenon (shouldn't be the case a the start of this scenario either and you should see the decrease in steam pressure).

Note that you can save the state of the simulation at any time in an ICD file. If you encounter this problem again, feel free to re-open this issue, and attach this file to a new comment.

Best regards.

**Comment by sandpatch** [comment]
Thanks for you very detailed responses. I somehow can't replicate it, maybe I did something as stupid as forgetting the steam seal.
Or maybe I had a too high pressure to repair the damages that I had. Either way not a bug but a user error. 
What maybe helped is that at every start I just repair everything from the drop down menu just to be safe.
Thanks again!
